name: 'CRDA'
description: 'Analyse Vulnerabilities in application dependencies'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  manifest_file_path:
    description: |
      Path of the manifest file to use for analysis.
      This path should not included the path where you checkout the repository
    required: true
  analysis_report_file_name:
    description: Name of the file to save the analysis report
    required: false
    default: crda_analysis_report
  snyk_token:
    description: Snyk token to be used to authenticate to CRDA
    required: false
  crda_key:
    description: Existing CRDA key to identify the existing user
    required: false
  consent_telemetry:
    description: |
      CRDA collects anonymous usage data, and is disabled by default.
      If you want this behaviour set this to true
    required: false
    default: "false"
  fail_on_vulnerability:
    description: |
      Fail the workflow if vulnerability is found in the project.
      This will lead to workflow failure and sarif file would not be obtained.
      To set failure when vulnerability severity level is either "error" or "warning" set this input to "error".
      By default it is set to fail when severity level is "warning",
      or if you don't want to fail the action set this input to "false"
    required: false
    default: "error"
  github_pat:
    description: Github personal access token to upload sarif to github
    required: false
    default: ${{ github.token }}
  upload_sarif:
    description: |
      Upload the generated sarif file, by default it is set to "true".
      If you don't want to upload sarif file set this input to "false"
    required: false
    default: "true"
  checkout_path:
    description: |
      Path at which the repository which is to be analyzed is checked out
    required: false
    default: ${{ github.workspace }}

outputs:
  crda_report_json:
    description: "Generated CRDA Analysis Report in JSON format"
  crda_report_sarif:
    description: "Generated CRDA Analysis Report in Sarif format"
  report_link:
    description: "CRDA analysis report link"

runs:
  using: 'node12'
  main: 'dist/index.js'
