name: Scan Golang project
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "windows-latest", "ubuntu-20.04" ]
        # Test once with explicit manifest_file, and once without
        manifest_file: [ "go.mod", "" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: Analyse Golang project
    steps:

      - name: Checkout action
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "0.2.3"
          
      - name: Run Go mod Tidy
        id: tidy 
        run: cd ./manifests/golang/ && go mod tidy

      - name: CRDA Scan
        id: scan
        uses: ./
        with:
          manifest_directory: manifests/golang/
          manifest_file: ${{ matrix.manifest_file }}
          crda_key: ${{ secrets.CRDA_KEY }}
          #snyk_token: ${{ secrets.SNYK_TOKEN }}
          fail_on: never

      - name: Print JSON analysis report
        if: ${{ always() && steps.scan.outputs.crda_report_json }}
        run: cat ${{ steps.scan.outputs.crda_report_json }}

      - name: Print SARIF analysis report
        if: ${{ always() && steps.scan.outputs.crda_report_sarif }}
        run: cat ${{ steps.scan.outputs.crda_report_sarif }}

      - name: Print Report Link
        run: echo ${{ steps.scan.outputs.report_link }}

      - name: Save intermediate files
        run: |
          mkdir -p uploads
          mv ${{ steps.scan.outputs.crda_report_json }} uploads
          mv ${{ steps.scan.outputs.crda_report_sarif }} uploads

      - name: Upload merged Results
        uses: actions/upload-artifact@v2
        with:
          name: scan_result_go.zip
          path: ./uploads
